# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
