# Generated by Django 2.0 on 2019-01-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_comment2',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
