# Generated by Django 2.0 on 2019-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comment_approved_comment2'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_comment3',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
