# Generated by Django 2.0 on 2019-01-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190118_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_comment3',
            new_name='approv_comment3',
        ),
    ]
