# Generated by Django 2.0 on 2019-01-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190118_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approv_comment3',
            new_name='approve_comment',
        ),
    ]
